# Database configuration for PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/java101
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate will automatically create the database schema on application startup and shutdown
spring.jpa.hibernate.ddl-auto=create

# Show SQL statements in the console for debugging purposes
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Initialize the data source after the application starts
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
